# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/api/django_project"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/infrastructure/rest-api"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/infrastructure/web-app"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/infrastructure/celery-worker"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/infrastructure/celery-flower"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/infrastructure/celery-scheduler"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/infrastructure/remote-dev"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/web-app/landing/"
    schedule:
      interval: "daily"
