# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/api/django_project" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/infrastructure/rest-api" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/infrastructure/celery-worker" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/infrastructure/celery-flower" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/infrastructure/celery-scheduler" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/infrastructure/remote-dev"
    schedule:
      interval: "weekly"
