# coding: utf-8

# flake8: noqa

"""
    REST API

    API for all things …

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from django_rest_api.api.sample_api import SampleApi
from django_rest_api.api_client import ApiClient

# import ApiClient
from django_rest_api.api_response import ApiResponse
from django_rest_api.configuration import Configuration
from django_rest_api.exceptions import (
    ApiAttributeError,
    ApiException,
    ApiKeyError,
    ApiTypeError,
    ApiValueError,
    OpenApiException,
)

# import models into sdk package
from django_rest_api.models.sample import Sample
