/* tslint:disable */
/* eslint-disable */
/**
 * REST API
 * API for all things …
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Sample,
} from '../models/index';
import {
    SampleFromJSON,
    SampleToJSON,
} from '../models/index';

/**
 * 
 */
export class SampleApi extends runtime.BaseAPI {

    /**
     * 
     */
    async retrieveSampleRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sample>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/sample/get`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SampleFromJSON(jsonValue));
    }

    /**
     * 
     */
    async retrieveSample(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sample> {
        const response = await this.retrieveSampleRaw(initOverrides);
        return await response.value();
    }

}
