# coding: utf-8

"""
    REST API

    API for all things …

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from django_rest_api.models.sample import Sample  # noqa: E501


class TestSample(unittest.TestCase):
    """Sample unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Sample:
        """Test Sample
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Sample`
        """
        model = Sample()  # noqa: E501
        if include_optional:
            return Sample(
                names = [
                    ''
                    ]
            )
        else:
            return Sample(
                names = [
                    ''
                    ],
        )
        """

    def testSample(self):
        """Test Sample"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
